# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geoff's Braindump
email: itzgeoff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A spot on the internet where I post random articles, notes, and things I have figured out.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itzg.github.io" # the base hostname & protocol for your site
twitter_username: itzg
github_username:  itzg
linkedin_username: itzgeoff

# Build settings
markdown: kramdown
